import template from './views/directory.ng.html'

angular.module('food-coop').config ($stateProvider) ->
  $stateProvider.state 'directory',
    url: '/directory'
    template: template
    controllerAs: 'dir'
    controller: 'directoryCtrl'
  return

# ---
# generated by js2coffee 2.1.0
