rolePromise = ($q, r) ->
  $q (resolve, reject) ->
    role = Roles.userIsInRole Meteor.userId(), r
    if role
      resolve role
    else
      reject 'FORBIDDEN'
    return

angular.module('food-coop').config ($stateProvider) ->
  $stateProvider
  .state 'myProducts',
    url: '/my-products'
    templateUrl: 'client/products/views/my-products.ng.html'
    controller: 'MyProductsCtrl'
    controllerAs: '$ctrl'
    resolve: 'currentUser': ($q) ->
      rolePromise($q, 'producer')
  return

# ---
# generated by js2coffee 2.1.0
