rolePromise = ($q, r) ->
  $q (resolve, reject) ->
    role = Roles.userIsInRole Meteor.userId(), r
    if role
      resolve role
    else
      reject 'FORBIDDEN'
    return

angular.module('food-coop').config ($stateProvider) ->
  $stateProvider
  .state('productDetails',
    url: '/product/:productId'
    templateUrl: 'client/products/views/product-details.ng.html'
    controller: 'ProductDetailsCtrl'
    controllerAs: 'ctrl')
  # .state 'productCreate',
  #   url: '/new-product'
  #   templateUrl: 'client/products/views/product-create.ng.html'
  #   controller: 'ProductCreateCtrl'
  #   controllerAs: 'ctrl'
  #   resolve: 'currentUser': ($q) ->
  #     rolePromise($q, 'producer')
  .state 'myProducts',
    url: '/my-products'
    templateUrl: 'client/products/views/my-products.ng.html'
    controller: 'MyProductsCtrl'
    controllerAs: '$ctrl'
    resolve: 'currentUser': ($q) ->
      rolePromise($q, 'producer')
  return

# ---
# generated by js2coffee 2.1.0
