angular.module('food-coop').controller 'CreateUserAdminCtrl', ($scope, $rootScope, $meteor, $stateParams, $mdToast) ->
  $scope.hubs = $meteor.collection(Hubs).subscribe('hubs')

  $scope.user = {}

  $scope.validate = (isValid) ->
    if isValid
      if $scope.user.password?
        $meteor.createUser $scope.user
        .then ->
          $scope.success()
          return
      else
        $meteor.call 'inviteUser', $scope.user, $scope.wholesaleBuyer
        .then ->
          $scope.success("invited user to join the Fresh Food Collective")
        , (err) ->
          console.log err
          $mdToast.show $mdToast.simple().content("Oops something went wrong, is that email already registered to a user?").position('bottom left').hideDelay(4000)
    else
      $scope.submitted = true
    return

  $scope.success = (message="Created Successfully")->
    $mdToast.show $mdToast.simple().content(message).position('bottom left').hideDelay(3000)
    $scope.user = {}
    return




  return

# ---
# generated by js2coffee 2.1.0
