angular.module('food-coop').controller 'ProductsAdminCtrl', ($scope, $mdToast) ->
  
  $scope.subscribe 'all-products'
  
  $scope.helpers
    products: () => return Products.find()
    
  $scope.save = (product, modifier) ->
    console.log product._id, modifier.toString()
    Products.update product._id, modifier
          

  return

# ---
# generated by js2coffee 2.1.0
