angular.module('food-coop').controller 'ProductsAdminCtrl', ($scope, $mdToast) ->
  
  $scope.subscribe 'all-products'
  
  $scope.helpers
    products: () => return Products.find()
    
  $scope.save = (product) ->
    Products.update product._id, 
      $set: published: product.published

  return

# ---
# generated by js2coffee 2.1.0
