angular.module('food-coop').controller 'ProductsAdminCtrl', ($scope, $mdToast, $reactive) ->
  $reactive(this).attach($scope)
  @subscribe 'all-products'
  
  @sort = name: 1
  
  @helpers
    products: () => return Products.find {}, {sort: @getReactively('sort') }
    
  @save = (product, modifier) ->
    Products.update product._id, modifier
          

  return

# ---
# generated by js2coffee 2.1.0
