angular.module('food-coop').controller 'TransactionCtrl', ($stateParams) ->

  this.transact = (amount) ->
    Meteor.users.update $stateParams.userId,
      $inc: 'profile.balance': amount
  return

  

# ---
# generated by js2coffee 2.1.0
