angular.module('food-coop').controller 'UserAdminCtrl', ($scope, $meteor, $stateParams, $mdToast) ->

  $scope.subscribe 'user', => 
    [$stateParams.userId]
    
  $scope.autorun ->
    $scope.user = Meteor.users.findOne($stateParams.userId)
    if $scope.user
      $scope.email = $scope.user.emails[0].address
    if Roles.userIsInRole $stateParams.userId, 'producer'
      $scope.producer = yes
    else
      $scope.producer = no
    return
    

 

  $scope.validate = (isValid) ->
    if isValid
      
      if $scope.email != Meteor.users.findOne($stateParams.userId).emails[0].address
        $scope.call 'addEmail', $scope.email, Meteor.users.findOne($stateParams.userId).emails[0].address, (err) ->
          if err
            console.log err
      
      Meteor.users.update $scope.user._id,
        $set: 'profile' : $scope.user.profile
      , (err) ->
        if err
          return console.log err
        $scope.success()
    else
      $scope.submitted = true
    return

  $scope.success = ->
    $mdToast.show $mdToast.simple().content('Saved Successfully').position('bottom left').hideDelay(3000)
    return
    
  $scope.changeRole = ->
    if $scope.producer == yes
      Meteor.call 'addRole', $scope.user._id, 'producer', () ->
        $mdToast.show $mdToast.simple().content('User is now a "Producer"').position('bottom left').hideDelay(3000)
      return
    else if $scope.producer == no
      Meteor.call 'removeRole', $scope.user._id, 'producer', () ->
        $mdToast.show $mdToast.simple().content('User is no longer a "Producer"').position('bottom left').hideDelay(3000)
    return



  return

# ---
# generated by js2coffee 2.1.0
