angular.module('food-coop').controller 'UserAdminCtrl', ($scope, $rootScope, $meteor, $stateParams, $mdToast) ->

  $scope.validate = (isValid) ->
    if isValid
      $scope.user.save().then (num) ->
        $scope.success()
        return
      , (err) ->
        console.log err
    else
      $scope.submitted = true
    return

  $scope.success = ->
    $mdToast.show $mdToast.simple().content('Saved Successfully').position('bottom left').hideDelay(3000)
    return

  $scope.$watch 'producer', (newValue, oldValue) ->
    if newValue and $scope.user? and oldValue != undefined
      $meteor.call('addRole', $scope.user._id, 'producer').then ->
          $mdToast.show $mdToast.simple().content('User is now a "Producer"').position('bottom left').hideDelay(3000)
      return
    else if not newValue and $scope.user? and oldValue != undefined
      $meteor.call('removeRole', $scope.user._id, 'producer').then ->
          $mdToast.show $mdToast.simple().content('User is no longer a "Producer"').position('bottom left').hideDelay(3000)

      return

  $scope.$meteorSubscribe('user',$stateParams.userId).then ->
    $scope.user = $scope.$meteorObject(Meteor.users, $stateParams.userId, false)

    if Roles.userIsInRole $stateParams.userId, 'producer'
      $scope.producer = yes
    else
      $scope.producer = no

  return

# ---
# generated by js2coffee 2.1.0
