// Meteor.methods({
//   'getBasicUser': function (id) {
//     check(id, String);
//     return Meteor.users.findOne({
//       _id: id,
//     }, {
//       fields: {
//         emails: 1,
//         'services.facebook.id': 1,
//         'profile.name': 1,
//       },
//     });
//   },
// });

// ---
// generated by coffee-script 1.9.2
