import template from './apply.ng.html'

angular.module('food-coop').config ($stateProvider) ->
  $stateProvider.state 'producer-application',
    url: '/apply'
    template: template
    controllerAs: 'ctrl'
    controller: 'ApplyCtrl'

  return

# ---
# generated by js2coffee 2.1.0
