angular.module('food-coop').config ($stateProvider) ->
  $stateProvider.state 'producer-application',
    url: '/apply'
    templateUrl: 'client/producer/apply.ng.html'
    controllerAs: 'ctrl'
    controller: 'ApplyCtrl'

  return

# ---
# generated by js2coffee 2.1.0
