angular.module('food-coop').config ($stateProvider) ->
  $stateProvider.state('policy',
    url: '/policy'
    templateUrl: 'client/static/legal/views/policy.ng.html'
  ).state('terms',
    url: '/terms-conditions'
    templateUrl: 'client/static/legal/views/terms.ng.html'
  ).state('privacy', 
    url: '/privacy-policy'
    templateUrl: 'client/static/legal/views/privacy.ng.html'
  ).state('customer-benefits', 
    url: '/features/customer'
    templateUrl: 'client/static/views/customer-benefits.ng.html'
  ).state('producer-benefits', 
    url: '/features/producer'
    templateUrl: 'client/static/views/producer-benefits.ng.html'
  )
  
  
  return

# ---
# generated by js2coffee 2.1.0
