isAdmin = (user) ->
  Roles.userIsInRole user, 'admin'



angular.module('food-coop').config ($stateProvider) ->
  $stateProvider.state('admin',
    url: '/dashboard'
    templateUrl: 'client/admin/views/admin.ng.html'
    controllerAs: 'rt'
    controller: 'AdminCtrl'
    resolve:
      'admin': ($auth) ->
        $auth.requireValidUser(isAdmin)
  ).state('admin.products',
    url: '/products'
    templateUrl: 'client/admin/views/products.ng.html'
    controller: 'ProductsAdminCtrl'
    controllerAs: 'ctrl'
  ).state('admin.users',
    url: '/users'
    templateUrl: 'client/admin/views/users.ng.html'
    controller: 'UsersAdminCtrl'
    resolve: 'admin': ($auth) ->
      $auth.requireValidUser(isAdmin)
  ).state('admin.createUser',
    url: '/user/new'
    templateUrl: 'client/admin/views/create-user.ng.html'
    controller: 'CreateUserAdminCtrl'
    resolve: 'admin': ($auth) ->
      $auth.requireValidUser(isAdmin)
  ).state('admin.user',
    url: '/user/:userId'
    templateUrl: 'client/admin/views/user.ng.html'
    controller: 'UserAdminCtrl'
    controllerAs: '$ctrl'
    resolve: 'admin': ($auth) ->
      $auth.requireValidUser(isAdmin)
  ).state('admin.userOrders',
    url: '/user/:userId/orders'
    templateUrl: 'client/admin/views/user.ng.html'
    controller: 'UserOrdersAdminCtrl'
    controllerAs: 'vm'
    resolve: 'admin': ($auth) ->
      $auth.requireValidUser(isAdmin)
  ).state('admin.order',
    url: '/order/:orderId'
    templateUrl: 'client/admin/views/order.ng.html'
    controller: 'OrderAdminCtrl'
    controllerAs: 'vm'
    resolve:
      'admin': ($auth) ->
        $auth.requireValidUser(isAdmin)
  ).state('admin.pos',
    url: '/pos/'
    template: "<point-of-sale></point-of-sale>"
    resolve:
      'admin': ($auth) ->
        $auth.requireValidUser(isAdmin)
  ).state('admin.payments',
    url: '/payments/'
    template: "<fc-payments></fc-payments>"
    resolve:
      'admin': ($auth) ->
        $auth.requireValidUser(isAdmin)
  ).state('admin.newPayment',
    url: '/new-payment/'
    template: "<new-payment></new-payment>"
    resolve:
      'admin': ($auth) ->
        $auth.requireValidUser(isAdmin)
  ).state('admin.cashOrders',
    url: '/cash-orders/'
    template: "<cash-orders></cash-orders>"
    resolve:
      'admin': ($auth) ->
        $auth.requireValidUser(isAdmin)
  )
  return

# ---
# generated by js2coffee 2.1.0
