import adminTemplate from './views/admin.ng.html'
import productsTemplate from './views/products.ng.html'
import usersTemplate from './views/users.ng.html'
import createuserTemplate from './views/create-user.ng.html'
import userTemplate from './views/user.ng.html'
import orderTemplate from './views/order.ng.html'


isAdmin = (user) ->
  Roles.userIsInRole user, 'admin'

angular.module('food-coop').config ($stateProvider) ->
  $stateProvider.state('admin',
    url: '/dashboard'
    template: adminTemplate
    controllerAs: 'rt'
    controller: 'AdminCtrl'
    resolve:
      'admin': ($auth) ->
        $auth.requireValidUser(isAdmin)
  ).state('admin.products',
    url: '/products'
    template: productsTemplate
    controller: 'ProductsAdminCtrl'
    controllerAs: 'ctrl'
  ).state('admin.users',
    url: '/users'
    template: usersTemplate
    controller: 'UsersAdminCtrl'
    resolve: 'admin': ($auth) ->
      $auth.requireValidUser(isAdmin)
  ).state('admin.createUser',
    url: '/user/new'
    template: createuserTemplate
    controller: 'CreateUserAdminCtrl'
    resolve: 'admin': ($auth) ->
      $auth.requireValidUser(isAdmin)
  ).state('admin.user',
    url: '/user/:userId'
    template: userTemplate
    controller: 'UserAdminCtrl'
    controllerAs: '$ctrl'
    resolve: 'admin': ($auth) ->
      $auth.requireValidUser(isAdmin)
  ).state('admin.userOrders',
    url: '/user/:userId/orders'
    template: userTemplate
    controller: 'UserOrdersAdminCtrl'
    controllerAs: 'vm'
    resolve: 'admin': ($auth) ->
      $auth.requireValidUser(isAdmin)
  ).state('admin.order',
    url: '/order/:orderId'
    template: orderTemplate
    controller: 'OrderAdminCtrl'
    controllerAs: 'vm'
    resolve:
      'admin': ($auth) ->
        $auth.requireValidUser(isAdmin)
  ).state('admin.pos',
    url: '/pos/'
    template: "<point-of-sale></point-of-sale>"
    resolve:
      'admin': ($auth) ->
        $auth.requireValidUser(isAdmin)
  ).state('admin.payments',
    url: '/payments/'
    template: "<fc-payments></fc-payments>"
    resolve:
      'admin': ($auth) ->
        $auth.requireValidUser(isAdmin)
  ).state('admin.newPayment',
    url: '/new-payment/'
    template: "<new-payment></new-payment>"
    resolve:
      'admin': ($auth) ->
        $auth.requireValidUser(isAdmin)
  ).state('admin.cashOrders',
    url: '/cash-orders/'
    template: "<cash-orders></cash-orders>"
    resolve:
      'admin': ($auth) ->
        $auth.requireValidUser(isAdmin)
  )
  return

# ---
# generated by js2coffee 2.1.0
