angular.module('food-coop').controller 'RegisterCtrl', ($meteor, $state) ->
  vm = this
  vm.credentials =
    email: ''
    password: ''
    profile:
      name: ""
      deliveryAddress: ""
      phone: ""

  vm.error = ''

  vm.role = 'customer'

  vm.prices =
    customer: Meteor.settings.public.shares.customer
    producer: Meteor.settings.public.shares.producer

  vm.register = ->
    $meteor.createUser(vm.credentials).then ((result) ->
      console.log result
      if vm.role == 'producer'
        $state.go 'producer-application'
      else
        $state.go 'store'
      return
    ), (err) ->
      vm.error = 'Registration error - ' + err
      return
    return

  vm.facebookLogin = ->
    $meteor.loginWithFacebook
      requestPermissions: ['email']
    .then (result) ->
      if vm.role == 'producer'
        $state.go 'producer-application'
      else
        $state.go 'profile.edit'
      console.log(result)
    , (err) ->
      console.error err
      vm.error = "Login Error: #{err}"

  return

# ---
# generated by js2coffee 2.1.0
