angular.module('food-coop').controller 'RegisterCtrl', ($scope, $reactive, $state) ->
  
  $reactive(this).attach($scope)
  
  vm = this
  vm.credentials =
    email: ''
    password: ''
    profile:
      name: ""
      deliveryAddress: ""
      phone: ""

  vm.error = ''

  vm.role = 'customer'

  vm.prices =
    customer: Meteor.settings.public.shares.customer
    producer: Meteor.settings.public.shares.producer

  vm.register = ->
    Accounts.createUser vm.credentials, vm.$bindToContext (err) =>
      if err
        console.log result
      else
        if vm.role == 'producer'
          $state.go 'producer-application'
        else
          $state.go 'store'
      return

  vm.facebookLogin = ->
    Meteor.loginWithFacebook
      requestPermissions: ['email']
    , vm.$bindToContext (err) ->
      if err
        console.error err
        vm.error = "Login Error: #{err}"
      else
        if vm.role == 'producer'
          $state.go 'producer-application'
        else
          $state.go 'profile.edit'
        console.log(result)

  return

# ---
# generated by js2coffee 2.1.0
