angular.module('food-coop').controller 'ResetCtrl',
($meteor, $state, $mdToast) ->
    vm = this
    vm.credentials = email: ''
    vm.error = ''

    vm.reset = ->
      $mdToast.show(
        $mdToast.simple()
        .content('Poof! Check your inbox for the email.')
        .position('top right')
        .hideDelay(3000)
      )
      $meteor.forgotPassword(vm.credentials).then (->
        $state.go 'store'
        return
      ), (err) ->
        vm.error = 'Error sending forgot password email - ' + err
        return
      return

    return vm


# ---
# generated by js2coffee 2.1.0
