
function loadMoreCtrl ($scope, $window) {

};

// ---
// generated by coffee-script 1.9.2

angular.module('food-coop').directive('scrollFire', function($window) {

  return {
    restrict: 'E',
    template: '',
    scope: {
      onView: '&'
    },
    link: function(scope, element, attr) {

      $($window).scroll( () => {
        let threshold;

        threshold = $($window).scrollTop() + $($window).height() - element.height();
        if (Math.floor(element.offset().top) <= threshold) {
          if (!element.data("visible")) {
            element.data("visible", true);
            console.log("reached the end!")
            scope.$apply(() => {
              scope.onView();
            });
          }
        } else if (element.data("visible")) {
          console.log("scrolling")
          element.data("visible", false);
        }
      })
    }
  }

})
