angular.module('food-coop').controller('navCtrl', function($mdUtil, $mdSidenav, $log, $state) {
  "ngInject";
  var buildToggler, vm;
  vm = this;
  buildToggler = function(navID) {
    var debounceFn;
    debounceFn = $mdUtil.debounce(function() {
      return $mdSidenav(navID).toggle().then(function() {
        return $log.debug("toggle " + navID + " is done");
      });
    }, 200);
    return debounceFn;
  };
  vm.toggleRight = buildToggler('right');
  vm.isProducer = function(user) {
    return Roles.userIsInRole(user, 'producer');
  };
  vm.goTo = function(route, params) {
    return $state.go(route, params);
  };
});

// ---
// generated by coffee-script 1.9.2